baseURL = "https://cyclofix.osm.be/"
languageCode = "en-us"
title = "CycloFix"
theme = "compose"

disableKinds = ["taxonomy"]

#  menu items
[[menu.main]]
  name = "Docs"
  weight = 2
  url = "docs/"

[[menu.main]]
  name = "Map"
  weight = 3
  url = "map/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

[params]
  author = "CycloFix Team"
  searchPlaceholder = "Search"
  repo = "https://github.com/osmbe/cyclofix-website"

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  [params.logo]
    lightMode = "cyclofix-logo.svg"
    darkMode = "cyclofix-logo.svg"

  [params.source]
    name = "GitHub"
    icon = "github.svg"
    url = "https://github.com/osmbe/cyclofix-website/"
